### ISSUE TITLE
[Feature] Session Room Timer

### ISSUE THREAD

**Issue by justindmyers** [PrincipleStudios/PlanningPoker#20]
As a user, I would like to be able to timebox story pointing an issue during a planning session

# Task List
- [ ] Create a component that allows the user to show a timer
- [ ] Allow setting timer with minutes
- [ ] Allow the timer to be canceled
- [ ] Allow the timer to be reset
